interface TimezoneInfo {
  timezone: string;
  city: string;
}

interface TimezoneGroup {
  region: string;
  timezones: TimezoneInfo[];
}

export const DEFAULT_TIMEZONES = {
  target: {
    timezone: "Europe/Nicosia",
    label: "Nicosia, Cyprus",
  },
};

export const TIMEZONE_GROUPS: TimezoneGroup[] = [
  {
    region: "Asia",
    timezones: [
      { timezone: "Asia/Kolkata", city: "New Delhi, Mumbai, Kolkata" },
      { timezone: "Asia/Dubai", city: "Dubai" },
      { timezone: "Asia/Tokyo", city: "Tokyo" },
      { timezone: "Asia/Singapore", city: "Singapore" },
      { timezone: "Asia/Shanghai", city: "Beijing, Shanghai" },
      { timezone: "Asia/Seoul", city: "Seoul" },
      { timezone: "Asia/Jakarta", city: "Jakarta" },
      { timezone: "Asia/Bangkok", city: "Bangkok" },
      { timezone: "Asia/Manila", city: "Manila" },
      { timezone: "Asia/Hong_Kong", city: "Hong Kong" },
      { timezone: "Asia/Kathmandu", city: "Kathmandu" },
      { timezone: "Asia/Karachi", city: "Karachi, Islamabad" },
      { timezone: "Asia/Colombo", city: "Colombo" },
      { timezone: "Asia/Almaty", city: "Almaty" },
      { timezone: "Asia/Yerevan", city: "Yerevan" },
    ],
  },
  {
    region: "Americas",
    timezones: [
      { timezone: "America/Los_Angeles", city: "Los Angeles, San Francisco" },
      { timezone: "America/New_York", city: "New York, Boston" },
      { timezone: "America/Chicago", city: "Chicago, Houston" },
      { timezone: "America/Toronto", city: "Toronto" },
      { timezone: "America/Vancouver", city: "Vancouver" },
      { timezone: "America/Sao_Paulo", city: "São Paulo" },
      { timezone: "America/Mexico_City", city: "Mexico City" },
      { timezone: "America/Bogota", city: "Bogotá" },
      { timezone: "America/Lima", city: "Lima" },
      { timezone: "America/Buenos_Aires", city: "Buenos Aires" },
      { timezone: "America/Caracas", city: "Caracas" },
      { timezone: "America/Montevideo", city: "Montevideo" },
      { timezone: "America/Santiago", city: "Santiago" },
    ],
  },
  {
    region: "Europe",
    timezones: [
      { timezone: "Europe/London", city: "London" },
      { timezone: "Europe/Paris", city: "Paris, Berlin, Rome" },
      { timezone: "Europe/Moscow", city: "Moscow" },
      { timezone: "Europe/Amsterdam", city: "Amsterdam" },
      { timezone: "Europe/Stockholm", city: "Stockholm" },
      { timezone: "Europe/Madrid", city: "Madrid" },
      { timezone: "Europe/Athens", city: "Athens" },
      { timezone: "Europe/Istanbul", city: "Istanbul" },
      { timezone: "Europe/Zurich", city: "Zurich" },
      { timezone: "Europe/Vienna", city: "Vienna" },
      { timezone: "Europe/Lisbon", city: "Lisbon" },
      { timezone: "Europe/Prague", city: "Prague" },
      { timezone: "Europe/Brussels", city: "Brussels" },
      { timezone: "Europe/Bucharest", city: "Bucharest" },
      { timezone: "Europe/Dublin", city: "Dublin" },
      { timezone: "Europe/Nicosia", city: "Cyprus" },
    ],
  },
  {
    region: "Africa",
    timezones: [
      { timezone: "Africa/Cairo", city: "Cairo" },
      { timezone: "Africa/Johannesburg", city: "Johannesburg" },
      { timezone: "Africa/Nairobi", city: "Nairobi" },
      { timezone: "Africa/Lagos", city: "Lagos" },
      { timezone: "Africa/Casablanca", city: "Casablanca" },
      { timezone: "Africa/Accra", city: "Accra" },
      { timezone: "Africa/Harare", city: "Harare" },
      { timezone: "Africa/Khartoum", city: "Khartoum" },
      { timezone: "Africa/Dakar", city: "Dakar" },
      { timezone: "Africa/Tunis", city: "Tunis" },
    ],
  },
  {
    region: "Pacific",
    timezones: [
      { timezone: "Pacific/Auckland", city: "Auckland" },
      { timezone: "Australia/Sydney", city: "Sydney" },
      { timezone: "Australia/Melbourne", city: "Melbourne" },
      { timezone: "Pacific/Fiji", city: "Fiji" },
      { timezone: "Pacific/Honolulu", city: "Honolulu" },
      { timezone: "Pacific/Port_Moresby", city: "Port Moresby" },
      { timezone: "Pacific/Tahiti", city: "Tahiti" },
      { timezone: "Pacific/Tongatapu", city: "Nukuʻalofa" },
    ],
  },
  {
    region: "Middle East",
    timezones: [
      { timezone: "Asia/Jerusalem", city: "Jerusalem" },
      { timezone: "Asia/Riyadh", city: "Riyadh" },
      { timezone: "Asia/Baghdad", city: "Baghdad" },
      { timezone: "Asia/Tehran", city: "Tehran" },
      { timezone: "Asia/Kuwait", city: "Kuwait City" },
      { timezone: "Asia/Muscat", city: "Muscat" },
      { timezone: "Asia/Amman", city: "Amman" },
      { timezone: "Asia/Beirut", city: "Beirut" },
    ],
  },
  {
    region: "Oceania",
    timezones: [
      { timezone: "Pacific/Guam", city: "Guam" },
      { timezone: "Pacific/Saipan", city: "Saipan" },
      { timezone: "Pacific/Noumea", city: "Noumea" },
      { timezone: "Pacific/Apia", city: "Apia" },
    ],
  },
];

export const LEGACY_TO_UPDATED_TIMEZONES: Record<string, string> = {
  "Africa/Asmera": "Africa/Asmara",
  "Africa/Timbuktu": "Africa/Bamako",
  "America/Argentina/ComodRivadavia": "America/Argentina/Catamarca",
  "America/Atka": "America/Adak",
  "America/Buenos_Aires": "America/Argentina/Buenos_Aires",
  "America/Catamarca": "America/Argentina/Catamarca",
  "America/Coral_Harbour": "America/Atikokan",
  "America/Cordoba": "America/Argentina/Cordoba",
  "America/Ensenada": "America/Tijuana",
  "America/Fort_Wayne": "America/Indiana/Indianapolis",
  "America/Indianapolis": "America/Indiana/Indianapolis",
  "America/Jujuy": "America/Argentina/Jujuy",
  "America/Knox_IN": "America/Indiana/Knox",
  "America/Louisville": "America/Kentucky/Louisville",
  "America/Mendoza": "America/Argentina/Mendoza",
  "America/Porto_Acre": "America/Rio_Branco",
  "America/Rosario": "America/Argentina/Cordoba",
  "America/Shiprock": "America/Denver",
  "America/Virgin": "America/Port_of_Spain",
  "Antarctica/South_Pole": "Antarctica/McMurdo",
  "Asia/Ashkhabad": "Asia/Ashgabat",
  "Asia/Calcutta": "Asia/Kolkata",
  "Asia/Chongqing": "Asia/Shanghai",
  "Asia/Chungking": "Asia/Shanghai",
  "Asia/Dacca": "Asia/Dhaka",
  "Asia/Harbin": "Asia/Shanghai",
  "Asia/Istanbul": "Europe/Istanbul",
  "Asia/Kashgar": "Asia/Urumqi",
  "Asia/Katmandu": "Asia/Kathmandu",
  "Asia/Macao": "Asia/Macau",
  "Asia/Rangoon": "Asia/Yangon",
  "Asia/Saigon": "Asia/Ho_Chi_Minh",
  "Asia/Tel_Aviv": "Asia/Jerusalem",
  "Asia/Thimbu": "Asia/Thimphu",
  "Asia/Ujung_Pandang": "Asia/Makassar",
  "Asia/Ulan_Bator": "Asia/Ulaanbaatar",
  "Atlantic/Faeroe": "Atlantic/Faroe",
  "Atlantic/Jan_Mayen": "Europe/Oslo",
  "Australia/ACT": "Australia/Sydney",
  "Australia/Canberra": "Australia/Sydney",
  "Australia/LHI": "Australia/Lord_Howe",
  "Australia/NSW": "Australia/Sydney",
  "Australia/North": "Australia/Darwin",
  "Australia/Queensland": "Australia/Brisbane",
  "Australia/South": "Australia/Adelaide",
  "Australia/Tasmania": "Australia/Hobart",
  "Australia/Victoria": "Australia/Melbourne",
  "Australia/West": "Australia/Perth",
  "Australia/Yancowinna": "Australia/Broken_Hill",
  "Brazil/Acre": "America/Rio_Branco",
  "Brazil/DeNoronha": "America/Noronha",
  "Brazil/East": "America/Sao_Paulo",
  "Brazil/West": "America/Manaus",
  "Canada/Atlantic": "America/Halifax",
  "Canada/Central": "America/Winnipeg",
  "Canada/Eastern": "America/Toronto",
  "Canada/Mountain": "America/Edmonton",
  "Canada/Newfoundland": "America/St_Johns",
  "Canada/Pacific": "America/Vancouver",
  "Canada/Yukon": "America/Whitehorse",
  CET: "Europe/Paris",
  "Chile/Continental": "America/Santiago",
  "Chile/EasterIsland": "Pacific/Easter",
  CST6CDT: "America/Chicago",
  Cuba: "America/Havana",
  Egypt: "Africa/Cairo",
  Eire: "Europe/Dublin",
  EST: "America/New_York",
  EST5EDT: "America/New_York",
  GB: "Europe/London",
  "GB-Eire": "Europe/London",
  GMT0: "Etc/GMT",
  Greenwich: "Etc/GMT",
  Hongkong: "Asia/Hong_Kong",
  Iceland: "Atlantic/Reykjavik",
  Iran: "Asia/Tehran",
  Israel: "Asia/Jerusalem",
  Jamaica: "America/Jamaica",
  Japan: "Asia/Tokyo",
  Kwajalein: "Pacific/Kwajalein",
  Libya: "Africa/Tripoli",
  "Mexico/BajaNorte": "America/Tijuana",
  "Mexico/BajaSur": "America/Mazatlan",
  "Mexico/General": "America/Mexico_City",
  NZ: "Pacific/Auckland",
  "NZ-CHAT": "Pacific/Chatham",
  Navajo: "America/Denver",
  PRC: "Asia/Shanghai",
  PST8PDT: "America/Los_Angeles",
  "Pacific/Johnston": "Pacific/Honolulu",
  "Pacific/Ponape": "Pacific/Pohnpei",
  "Pacific/Samoa": "Pacific/Pago_Pago",
  "Pacific/Truk": "Pacific/Chuuk",
  "Pacific/Yap": "Pacific/Chuuk",
  Poland: "Europe/Warsaw",
  Portugal: "Europe/Lisbon",
  ROC: "Asia/Taipei",
  ROK: "Asia/Seoul",
  Singapore: "Asia/Singapore",
  Turkey: "Europe/Istanbul",
  UCT: "Etc/UCT",
  "US/Alaska": "America/Anchorage",
  "US/Aleutian": "America/Adak",
  "US/Arizona": "America/Phoenix",
  "US/Central": "America/Chicago",
  "US/East-Indiana": "America/Indiana/Indianapolis",
  "US/Eastern": "America/New_York",
  "US/Hawaii": "Pacific/Honolulu",
  "US/Indiana-Starke": "America/Indiana/Knox",
  "US/Michigan": "America/Detroit",
  "US/Mountain": "America/Denver",
  "US/Pacific": "America/Los_Angeles",
  "US/Pacific-New": "America/Los_Angeles",
  "US/Samoa": "Pacific/Pago_Pago",
  "W-SU": "Europe/Moscow",
  Zulu: "Etc/UTC",
  "Etc/UTC": "UTC",
  "Etc/GMT": "UTC",
  "Etc/UCT": "UTC",
};
